### ISSUE TITLE
Add option to not create new class if nothing changed

### ISSUE THREAD

**Issue by dalewking** [numen31337/copy_with_extension#20]
When I have hand written copy with methods I have followed this pattern to optimize for not creating a new object if nothing changed:
```
  Row copyWith({
    BuiltList<CellState> cells,
    CellState lock,
  }) {
    cells ??= this._cells;
    lock ??= this.lock;

    if (cells != this._cells || lock != this.lock) {
      return Row(names, cells, _computeScore(cells), lock);
    } else {
      return this;
    }
  }
```
Would be nice to have that as an option as it may help in flutter with eliminating unnecessary rebuilds

**Comment by numen31337** [comment]
Thank you for the suggestion. This library follows the convention used by [the Flutter library itself](https://github.com/flutter/flutter/blob/f30b7f4db9/packages/flutter/lib/src/material/text_theme.dart#L385). In my opinion, this kind of behaviour can do more harm than good. Most importantly when the user of an API calls a function called `copy` they expect to get a copy of the object instead of the same instance. Another point is that here we will implicitly rely on the comparison operator which can also cause some unexpected behaviour for the user. For cases where the optimisation is really needed it is easy to achieve it exactly when it needed and avoid any premature optimisations.

**Comment by dalewking** [comment]
That was the point of making it an option, you have to opt-in to the behavior

**Comment by dalewking** [comment]
It is a big deal when using it for redux state because new instances will lead to unnecessary rebuilds.
